# ══════════════════════════════════════════════════════════════════════════════
# streamlit_catboost_app.py
# Run with:  streamlit run streamlit_catboost_app.py
# Requires:  CatBoost_package.pkl  (generated by CatBoost_Package.py)
# ══════════════════════════════════════════════════════════════════════════════

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import random
import plotly.graph_objects as go
import warnings
warnings.filterwarnings("ignore")

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="CatBoost Adsorption Predictor",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Styling ────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
[data-testid="stAppViewContainer"] {background: #f0f4f8;}
[data-testid="stSidebar"]          {background: #1a2e3b; color: white;}
[data-testid="stSidebar"] *        {color: white !important;}

.card {
    background: white;
    border-radius: 12px;
    padding: 20px 24px 14px 24px;
    margin-bottom: 18px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}
.card-title {
    font-size: 15px; font-weight: 700; letter-spacing: .5px;
    margin-bottom: 10px; padding-bottom: 6px; border-bottom: 2px solid;
    display: flex; align-items: center; gap: 7px;
}
.cat1-title {border-color: #2b9c8f; color: #2b9c8f;}
.cat2-title {border-color: #7c4daa; color: #7c4daa;}
.cat3-title {border-color: #d9641e; color: #d9641e;}

.page-title    {font-size: 28px; font-weight: 800; color: #0d1f2d; margin-bottom: 4px;}
.page-subtitle {font-size: 15px; color: #2c3e50; font-weight: 500; margin-bottom: 0px;}

.ratio-box   {background: #eef6f5; border: 1.5px solid #2b9c8f; border-radius: 8px;
               padding: 8px 12px; margin-top: 4px; margin-bottom: 10px;}
.ratio-label {font-size: 12px; color: #555; font-weight: 600; margin-bottom: 2px;}
.ratio-value {font-size: 22px; font-weight: 800; color: #1a7a6e;}

.result-box   {background: linear-gradient(135deg, #1a2e3b 0%, #2b5870 100%);
                border-radius: 14px; padding: 28px 24px; text-align: center;
                color: white; margin-top: 16px; box-shadow: 0 4px 18px rgba(26,46,59,0.25);}
.result-label {font-size: 16px; opacity: .75; margin-bottom: 6px;}
.result-value {font-size: 52px; font-weight: 800; letter-spacing: -1px;}
.result-unit  {font-size: 20px; opacity: .65;}
.result-sub   {font-size: 13px; opacity: .6; margin-top: 8px;}

.metric-card  {background: white; border-radius: 10px; padding: 14px 18px;
                box-shadow: 0 1px 6px rgba(0,0,0,0.07); text-align: center;}
.metric-label {font-size: 12px; color: #666; font-weight: 600; margin-bottom: 4px;}
.metric-val   {font-size: 22px; font-weight: 800; color: #1a2e3b;}
.metric-std   {font-size: 12px; color: #888;}

div[data-testid="stButton"] > button {
    background: linear-gradient(135deg, #2b9c8f, #1a7a6e) !important;
    color: white !important; font-size: 17px !important; font-weight: 700 !important;
    border-radius: 10px !important; padding: 14px 40px !important; border: none !important;
    width: 100%; box-shadow: 0 3px 10px rgba(43,156,143,.35) !important;
}
div[data-testid="stButton"] > button:hover {filter: brightness(1.1);}

[data-testid="stNumberInput"] label, [data-testid="stSelectbox"] label,
div[data-testid="stWidgetLabel"] p, div[data-testid="stWidgetLabel"] label {
    color: #111111 !important; font-weight: 600 !important;
}
</style>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# LOAD PACKAGE
# ══════════════════════════════════════════════════════════════════════════════
PKG_PATH = "CatBoost_package.pkl"

@st.cache_resource(show_spinner="Loading CatBoost model…")
def load_package(path):
    return joblib.load(path)

try:
    pkg = load_package(PKG_PATH)
except FileNotFoundError:
    st.error(f"**Package not found:** `{PKG_PATH}` — run `CatBoost_Package.py` first.")
    st.stop()

model              = pkg['model']
feature_names      = pkg['feature_names']
categorical_cols   = pkg['categorical_cols']
numerical_cols     = pkg['numerical_cols']
biomass_values     = pkg['biomass_values']
pollutant_values   = pkg['pollutant_values']
cv_results         = pkg['cv_results']
train_metrics_f    = pkg['train_metrics_final']
test_metrics_f     = pkg['test_metrics_final']
oof_preds          = pkg['oof_preds']
oof_actuals        = pkg['oof_actuals']
y_train_arr        = pkg['y_train']
train_preds_final  = pkg['train_preds_final']
y_test_arr         = pkg['y_test']
test_preds_final   = pkg['test_preds_final']
feat_importances   = pkg['feat_importances']

# ── Feature groupings (adjust slice indices to match your actual feature list) ─
GROUPS = {
    "🔥 Pyrolysis Conditions":    feature_names[0:4],
    "🧬 Biochar Characteristics": feature_names[4:15],
    "⚗️  Adsorption Conditions":  feature_names[15:],
}
GROUP_CLASSES = {
    "🔥 Pyrolysis Conditions":    "cat1",
    "🧬 Biochar Characteristics": "cat2",
    "⚗️  Adsorption Conditions":  "cat3",
}

C_COL  = 'C (%)'
H_COL  = 'H (%)'
O_COL  = 'O (%)'
HC_COL = 'H/C'
OC_COL = 'O/C'
AUTO_COMPUTED = {HC_COL, OC_COL}

RANDOM_RANGES = {
    'C (%)':                 (30.0,  85.0),
    'H (%)':                 (1.0,   6.0),
    'O (%)':                 (3.0,   35.0),
    'N (%)':                 (0.1,   5.0),
    'Pyrolysis temperature': (300.0, 900.0),
    'Heating rate':          (1.0,   50.0),
    'Residence time':        (0.5,   4.0),
    'BET surface area':      (1.0,   1500.0),
    'Pore volume':           (0.01,  1.0),
    'Pore size':             (1.0,   20.0),
    'pH':                    (2.0,   12.0),
    'Temperature':           (15.0,  60.0),
    'Initial concentration': (10.0,  500.0),
    'Dose':                  (0.1,   5.0),
    'Contact time':          (10.0,  1440.0),
}
DEFAULT_RANGE = (1.0, 100.0)

# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("## 🌿 CatBoost Predictor")
    st.markdown("---")
    st.markdown("**Model:** CatBoostRegressor")
    st.markdown(f"**Features:** {len(feature_names)}")
    st.markdown(f"**Categoricals:** {', '.join(categorical_cols)}")
    st.markdown("---")

    st.markdown("### 📊 Model Performance")
    r2_v  = cv_results['R2']['val_mean']
    r2_vs = cv_results['R2']['val_std']
    r2_t  = test_metrics_f['R2']
    rmse_v  = cv_results['RMSE']['val_mean']
    rmse_vs = cv_results['RMSE']['val_std']
    rmse_t  = test_metrics_f['RMSE']
    st.markdown(f"**R² Validation:** {r2_v:.4f} ± {r2_vs:.4f}")
    st.markdown(f"**R² Test:**        {r2_t:.4f}")
    st.markdown(f"**RMSE Validation:** {rmse_v:.4f} ± {rmse_vs:.4f}")
    st.markdown(f"**RMSE Test:**       {rmse_t:.4f}")
    st.markdown("---")

    st.markdown("### ℹ️ How to use")
    st.markdown(
        "1. Fill in feature values below\n"
        "2. H/C and O/C update automatically\n"
        "3. Press **Predict** to get Qe\n"
        "4. Use **Random Sample** to explore"
    )
    st.markdown("---")

    if st.button("🎲 Fill Random Sample", key="rand_btn", use_container_width=True):
        for f in feature_names:
            if f == 'Biomass':
                st.session_state[f'inp_{f}'] = random.choice(biomass_values)
            elif f == 'Pollutant':
                st.session_state[f'inp_{f}'] = random.choice(pollutant_values)
            elif f not in AUTO_COMPUTED:
                lo, hi = RANDOM_RANGES.get(f, DEFAULT_RANGE)
                st.session_state[f'inp_{f}'] = round(random.uniform(lo, hi), 4)
        st.rerun()

# ══════════════════════════════════════════════════════════════════════════════
# PAGE HEADER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown(
    '<p class="page-title">🌿 Biochar Adsorption Capacity Predictor</p>'
    '<p class="page-subtitle">Predict equilibrium adsorption capacity '
    '<b>Qe (mg/g)</b> using a CatBoost model with native categorical support '
    'and Optuna-tuned hyperparameters.</p>',
    unsafe_allow_html=True
)
st.markdown("---")

# ══════════════════════════════════════════════════════════════════════════════
# INPUT FORM
# ══════════════════════════════════════════════════════════════════════════════
input_vals = {}
form_cols  = st.columns(len(GROUPS))

for col_obj, (group_name, group_features) in zip(form_cols, GROUPS.items()):
    cls = GROUP_CLASSES[group_name]
    with col_obj:
        st.markdown(
            f'<div class="card">'
            f'<div class="card-title {cls}-title">{group_name}</div>',
            unsafe_allow_html=True,
        )

        for feat in group_features:

            if feat == 'Biomass':
                cur = st.session_state.get(f'inp_{feat}', biomass_values[0])
                idx = biomass_values.index(cur) if cur in biomass_values else 0
                val = st.selectbox("Biomass", biomass_values, index=idx,
                                   key=f'inp_{feat}',
                                   help="Feedstock type used to produce biochar")
                input_vals[feat] = val

            elif feat == 'Pollutant':
                cur = st.session_state.get(f'inp_{feat}', pollutant_values[0])
                idx = pollutant_values.index(cur) if cur in pollutant_values else 0
                val = st.selectbox("Pollutant", pollutant_values, index=idx,
                                   key=f'inp_{feat}',
                                   help="Target pollutant for adsorption")
                input_vals[feat] = val

            elif feat in AUTO_COMPUTED:
                c_now = float(st.session_state.get(f'inp_{C_COL}', 0.0) or 0.0)
                h_now = float(st.session_state.get(f'inp_{H_COL}', 0.0) or 0.0)
                o_now = float(st.session_state.get(f'inp_{O_COL}', 0.0) or 0.0)

                if feat == HC_COL:
                    live_val = round(h_now / c_now, 4) if c_now > 0 else 0.0
                else:
                    live_val = round(o_now / c_now, 4) if c_now > 0 else 0.0

                st.markdown(
                    f'<div class="ratio-box">'
                    f'<div class="ratio-label">{feat} &nbsp;(auto-calculated)</div>'
                    f'<div class="ratio-value">{live_val:.4f}</div>'
                    f'</div>',
                    unsafe_allow_html=True
                )
                input_vals[feat] = live_val

            else:
                val = st.number_input(
                    feat,
                    value=float(st.session_state.get(f'inp_{feat}', 0.0)),
                    format="%.4f",
                    key=f'inp_{feat}'
                )
                input_vals[feat] = val

        st.markdown('</div>', unsafe_allow_html=True)

# Sync ratios for prediction
c_val = float(input_vals.get(C_COL, 0.0) or 0.0)
h_val = float(input_vals.get(H_COL, 0.0) or 0.0)
o_val = float(input_vals.get(O_COL, 0.0) or 0.0)
input_vals[HC_COL] = round(h_val / c_val, 4) if c_val > 0 else 0.0
input_vals[OC_COL] = round(o_val / c_val, 4) if c_val > 0 else 0.0

# ══════════════════════════════════════════════════════════════════════════════
# PREDICT BUTTON
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("")
_, btn_col, _ = st.columns([1, 2, 1])
with btn_col:
    predict_clicked = st.button("⚡ Predict Qe (mg/g)", key="predict_btn")

# ══════════════════════════════════════════════════════════════════════════════
# RESULT
# ══════════════════════════════════════════════════════════════════════════════
if predict_clicked:
    errors = []
    numeric_vals = [v for k, v in input_vals.items()
                    if k not in categorical_cols and isinstance(v, (int, float))]
    if any(v < 0 for v in numeric_vals):
        errors.append("All numeric inputs must be ≥ 0.")
    if c_val <= 0:
        errors.append("C (%) must be > 0 to compute H/C and O/C ratios.")

    if errors:
        for e in errors:
            st.error(f"❌ {e}")
    else:
        with st.spinner("Running CatBoost model…"):
            try:
                row = pd.DataFrame([input_vals])
                for col in categorical_cols:
                    row[col] = row[col].astype(str)
                row = row[feature_names]
                qe  = float(model.predict(row)[0])

                _, res_col, _ = st.columns([1, 2, 1])
                with res_col:
                    st.markdown(
                        f"""
                        <div class="result-box">
                            <div class="result-label">Predicted Equilibrium Adsorption Capacity</div>
                            <div class="result-value">{qe:.2f}</div>
                            <div class="result-unit">mg / g</div>
                            <div class="result-sub">CatBoost · Optuna-tuned · 5-fold Nested CV</div>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

            except Exception as ex:
                st.error(f"⚠️ Prediction failed: {ex}")
                st.exception(ex)

# ══════════════════════════════════════════════════════════════════════════════
# TABS: Performance & Feature Importance
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("---")
tab_perf, tab_scatter, tab_fi = st.tabs(
    ["📊 Performance Metrics", "🔵 Scatter Plot", "🏆 Feature Importance"]
)

# ── Tab 1: Full metrics table ─────────────────────────────────────────────────
with tab_perf:
    st.markdown("#### Nested CV + Held-out Test Metrics")

    key_metrics = ['R2', 'AR2', 'EVS', 'RMSE', 'MAE', 'MAPE', 'SMAPE', 'RSR', 'CVRMSE', 'RAE']
    rows = []
    for mn in key_metrics:
        r = cv_results[mn]
        rows.append({
            'Metric'          : mn,
            'Train (mean)'    : f"{r['train_mean']:.4f}",
            'Train (± std)'   : f"± {r['train_std']:.4f}",
            'Val (mean)'      : f"{r['val_mean']:.4f}",
            'Val (± std)'     : f"± {r['val_std']:.4f}",
            'Test (held-out)' : f"{test_metrics_f[mn]:.4f}",
        })
    st.dataframe(pd.DataFrame(rows).set_index('Metric'), use_container_width=True)

    # Summary cards for key metrics
    st.markdown("#### Key Metric Cards")
    card_metrics = ['R2', 'RMSE', 'MAE', 'SMAPE']
    cols = st.columns(len(card_metrics))
    for col_obj, mn in zip(cols, card_metrics):
        r = cv_results[mn]
        with col_obj:
            st.markdown(
                f'<div class="metric-card">'
                f'<div class="metric-label">{mn}</div>'
                f'<div class="metric-val">{r["val_mean"]:.4f}</div>'
                f'<div class="metric-std">± {r["val_std"]:.4f} (val) &nbsp;|&nbsp; '
                f'{test_metrics_f[mn]:.4f} (test)</div>'
                f'</div>',
                unsafe_allow_html=True
            )

# ── Tab 2: Scatter plot ───────────────────────────────────────────────────────
with tab_scatter:
    st.markdown("#### Actual vs Predicted — Train / Validation (OOF) / Test")

    fig = go.Figure()

    # Train (final model on full X_train)
    fig.add_trace(go.Scatter(
        x=y_train_arr, y=train_preds_final,
        mode='markers',
        marker=dict(color='red', size=7, opacity=0.6,
                    line=dict(color='black', width=0.8)),
        name=f'Train  R²={train_metrics_f["R2"]:.3f}'
    ))

    # Validation OOF
    mask = ~np.isnan(oof_preds)
    fig.add_trace(go.Scatter(
        x=oof_actuals[mask], y=oof_preds[mask],
        mode='markers',
        marker=dict(color='royalblue', size=7, opacity=0.6,
                    line=dict(color='black', width=0.8)),
        name=f'Validation (OOF)  R²={cv_results["R2"]["val_mean"]:.3f} ± {cv_results["R2"]["val_std"]:.3f}'
    ))

    # Test
    fig.add_trace(go.Scatter(
        x=y_test_arr, y=test_preds_final,
        mode='markers',
        marker=dict(color='green', size=9, opacity=0.8,
                    line=dict(color='black', width=1)),
        name=f'Test  R²={test_metrics_f["R2"]:.3f}'
    ))

    # Ideal line
    lim = max(
        float(np.nanmax(y_train_arr)), float(np.nanmax(y_test_arr)),
        float(np.nanmax(train_preds_final)), float(np.nanmax(test_preds_final))
    ) * 1.05
    fig.add_trace(go.Scatter(
        x=[0, lim], y=[0, lim],
        mode='lines',
        line=dict(color='black', dash='dash', width=1.5),
        name='Ideal Line'
    ))

    fig.update_layout(
        xaxis_title='Actual Qe (mg/g)',
        yaxis_title='Predicted Qe (mg/g)',
        title=dict(text='CatBoost — Actual vs Predicted', font=dict(size=18)),
        legend=dict(bgcolor='rgba(255,255,255,0.85)', bordercolor='#ccc', borderwidth=1),
        plot_bgcolor='white',
        paper_bgcolor='white',
        width=650, height=600,
        xaxis=dict(range=[0, lim], showgrid=True, gridcolor='#eee', zeroline=False),
        yaxis=dict(range=[0, lim], showgrid=True, gridcolor='#eee', zeroline=False),
    )
    fig.update_yaxes(scaleanchor='x', scaleratio=1)
    st.plotly_chart(fig, use_container_width=True)

# ── Tab 3: Feature importance ─────────────────────────────────────────────────
with tab_fi:
    st.markdown("#### CatBoost Feature Importances (PredictionValuesChange)")

    fi_df = (pd.DataFrame.from_dict(feat_importances, orient='index', columns=['Importance'])
               .sort_values('Importance', ascending=True))

    colors = ['#2b9c8f' if v >= fi_df['Importance'].quantile(0.75)
              else '#7c4daa' if v >= fi_df['Importance'].quantile(0.5)
              else '#d9641e' if v >= fi_df['Importance'].quantile(0.25)
              else '#aaa'
              for v in fi_df['Importance']]

    fig_fi = go.Figure(go.Bar(
        x=fi_df['Importance'],
        y=fi_df.index,
        orientation='h',
        marker_color=colors,
        marker_line=dict(color='black', width=0.5),
    ))
    fig_fi.update_layout(
        xaxis_title='Importance (%)',
        yaxis_title='',
        title=dict(text='Feature Importance', font=dict(size=17)),
        plot_bgcolor='white',
        paper_bgcolor='white',
        height=max(400, len(feature_names) * 32),
        margin=dict(l=160, r=20, t=50, b=40),
        xaxis=dict(showgrid=True, gridcolor='#eee'),
    )
    st.plotly_chart(fig_fi, use_container_width=True)

# ══════════════════════════════════════════════════════════════════════════════
# FOOTER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("---")
st.markdown(
    "<p style='text-align:center; color:#888; font-size:13px;'>"
    "CatBoostRegressor · Optuna HPO · 5-fold Nested CV · "
    "Zero Data Leakage · Train / Val / Test split</p>",
    unsafe_allow_html=True,
)
